### PR TITLE
ZEP0001 to active

### PR DESCRIPTION
**Pull request by jhamman**
This moves ZEP0001 to the active directory and updates the status in the document.

### CODE REVIEW

**Comment by normanrz** [comment]
Could there be a redirect from the draft URL to the active URL?

**Comment by MSanKeys963** [comment]
Thanks for looking this over and sending the PR, @jhamman.

Based on the discussions from previous ZEP meetings, we decided to add a contributors section in the ZEP0001 to include the names of community members who helped us finalise the spec.

I've added #43 to include the list and also changed the status from Draft → Accepted.

Please have a look at it. Thank you!

**Comment by jhamman** [comment]
Thanks @MSanKeys963 -- do you want to close this then? It looks like you've started off a fresh branch so only one of these should go in.

**Comment by MSanKeys963** [comment]
@jhamman -  Apologies for not updating this branch.
Let's close this and continue over at #43.

**Pull request closed without merging**
