### PR TITLE
update ZEP0002

### PR DESCRIPTION
**Pull request by normanrz**
Update ZEP2 to match the current version of the draft spec.

### CODE REVIEW

**Comment by normanrz** [comment]
Also fixed the RTD builds.

**Comment by normanrz** [comment]
@MSanKeys963 please review and merge if approved.

**Review by jstriebel — APPROVED** [review]
LGTM 👍

**Review by MSanKeys963 — APPROVED** [review]

**Comment by MSanKeys963** [comment]
LGTM. Thanks for working on this, @normanrz.

**Pull request merged**
